spring:
  #数据库连接参数
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: yeyeye88
    url: jdbc:mysql://localhost:3306/onlinedoctor?serverTimezone=UTC&characterEnconding=utf-8
  mail:
    username: 1363293513@qq.com
    password: bwxbtjizuetxiceg
    host: smtp.qq.com
    default-encoding: utf-8       # 编码,默认UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true          # 安全的ssl链接

  # 配置 Redis
  redis:
    host: 123.57.227.61
    port: 6379
    password: 991001

  #配置es集群
  elasticsearch:
    rest:
      uris: http://123.57.227.61:9200,http://123.57.227.61:9200

# mybatis 相关
mybatis:
  # 扫描****mapper.xml的配置在哪里
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8080

#logging:
#  config: logback.xml
#  level:
#    com.itcodai.course03.dao: trace
#logging:
#  level:
#    root: info
